### ISSUE TITLE
SynchronizationContextCollection<T> で誤った要素が削除される

### ISSUE THREAD

**Issue by veigr** [ugaya40/StatefulModel#2]
### 概要

`ToSyncedSynchronizationContextCollection()` により作成した `SynchronizationContextCollection<T>` において、ソース コレクションの要素を削除した場合に異なる要素が削除されてしまう問題があります。

削除だけの問題では無い気がしますが、一番分かりやすい問題であったため、このようなタイトルとしています。
### 環境
- Windows 10 Pro 10586.218
- Visual Studio 2015 Enterprise Update 2
- .NET Framework 4.6.1
### 再現手順

StatefulModel 0.5 をインストールした WPF アプリケーションにて、以下のようなコード(MainWindow.xaml.cs)を実行します。
- StatefulModel 0.5
- WPF アプリケーション テンプレート
- TargetFrameworkVersion 4.6.1

```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Threading;
using StatefulModel;

namespace WpfApplication1
{
    /// <summary>
    /// MainWindow.xaml の相互作用ロジック
    /// </summary>
    public partial class MainWindow : Window
    {
        private ObservableSynchronizedCollection<int> source;
        private SynchronizationContextCollection<int> result;

        public MainWindow()
        {
            this.InitializeComponent();


            this.source = new ObservableSynchronizedCollection<int>(Enumerable.Range(1, 5));

            var context = new DispatcherSynchronizationContext(Application.Current.Dispatcher);
            this.result = this.source.ToSyncedSynchronizationContextCollection(context);
            // SynchronizationContext の Post でコレクション操作されてるので、この時点では result の要素数は 0
        }

        private void ButtonBase_OnClick(object sender, RoutedEventArgs e)
        {
            this.source.Remove(1);
            // 上記同様この時点ではまだ result に削除は反映されない
            Application.Current.Dispatcher.BeginInvoke((Action)this.Dump);
        }

        private void Dump()
        {
            // ソース コレクションでは 1 が削除されているが、 SynchronizationContextCollection 側は 5 が削除されてしまっている
            Console.WriteLine("source:");
            this.source.ToList().ForEach(Console.WriteLine);
            Console.WriteLine("result:");
            this.result.ToList().ForEach(Console.WriteLine);
        }
    }
}
```
### 原因

根本的な原因は何なのかというのは設計の問題となりそうなので判断が難しいところなのですが、直接的な原因は以下の2点となります。
1. `ToSyncedSynchronizationContextCollection()` した際に、ソース コレクションとは逆の順序で要素が挿入されてしまう
2. ソース コレクションから要素を `Remove()` した際、同期している `SynchronizationContextCollection<T>` からも同じ index にある要素を削除するが、順序が逆になってしまっているために誤った要素を削除してしまう
##### 1 の詳細
- `ToSyncedSynchronizationContextCollection()` 内では `InsertItem(int index, T newItem)` にて指定された index 位置に要素を追加する処理が行われる
- 実際の要素追加は `SynchronizationContext.Post()` によって非同期に実行されるので、即座には追加されない
- index 位置はその時点でのコレクション末尾を計算して渡している
- しかし index は親クラスの `NotifyChangedCollection<T>.Add()` 内にて　`ToSyncedSynchronizationContextCollection()` 実行時点に計算されたものであるため、まだ要素が追加されておらず、 `SynchronizationContext.Post()` では常に 0 番目に要素を追加するという処理になってしまっている
- そのため、順序が反転した `SynchronizationContextCollection<T>` が出来上がってしまう

**Comment by ugaya40** [comment]
ありがとうございます！治して0.6をリリースしました！
